# ZSH CONFIG
UPDATE_ZSH_DAYS=10
DISABLE_UNTRACKED_FILES_DIRTY="false"
COMPLETION_WAITING_DOTS="true"
HYPHEN_INSENSITIVE="false"
DISABLE_AUTO_UPDATE="false"
DISABLE_LS_COLORS="false"
DISABLE_AUTO_TITLE="false"
ENABLE_CORRECTION="false"
CASE_SENSITIVE="false"
HIST_STAMPS="dd.mm.yyyy" |

# PLUGINS

# ZSH FUZZY
[ -f $ZSH_CUSTOM/plugins/.fzf.zsh ] && source $ZSH_CUSTOM/plugins/.fzf.zsh
